interface AirportSeed {
  city: string;
  country: string;
  iata: string;
  icao: string;
  latitude: number;
  longitude: number;
  name: string;
}

export const airportSeed: AirportSeed[] = [
  {
    city: 'Atlanta',
    country: 'United States',
    iata: 'ATL',
    icao: 'KATL',
    latitude: 33.6367,
    longitude: -84.4281,
    name: 'Hartsfield-Jackson Atlanta International Airport',
  },
  {
    city: 'Los Angeles',
    country: 'United States',
    iata: 'LAX',
    icao: 'KLAX',
    latitude: 33.9425,
    longitude: -118.4081,
    name: 'Los Angeles International Airport',
  },
  {
    city: 'Chicago',
    country: 'United States',
    iata: 'ORD',
    icao: 'KORD',
    latitude: 41.9786,
    longitude: -87.9048,
    name: "O'Hare International Airport",
  },
  {
    city: 'Dallas',
    country: 'United States',
    iata: 'DFW',
    icao: 'KDFW',
    latitude: 32.8969,
    longitude: -97.038,
    name: 'Dallas/Fort Worth International Airport',
  },
  {
    city: 'Denver',
    country: 'United States',
    iata: 'DEN',
    icao: 'KDEN',
    latitude: 39.8617,
    longitude: -104.6732,
    name: 'Denver International Airport',
  },
  {
    city: 'New York',
    country: 'United States',
    iata: 'JFK',
    icao: 'KJFK',
    latitude: 40.6398,
    longitude: -73.7789,
    name: 'John F. Kennedy International Airport',
  },
  {
    city: 'San Francisco',
    country: 'United States',
    iata: 'SFO',
    icao: 'KSFO',
    latitude: 37.6189,
    longitude: -122.375,
    name: 'San Francisco International Airport',
  },
  {
    city: 'Seattle',
    country: 'United States',
    iata: 'SEA',
    icao: 'KSEA',
    latitude: 47.4489,
    longitude: -122.3094,
    name: 'Seattle-Tacoma International Airport',
  },
  {
    city: 'Miami',
    country: 'United States',
    iata: 'MIA',
    icao: 'KMIA',
    latitude: 25.7932,
    longitude: -80.2906,
    name: 'Miami International Airport',
  },
  {
    city: 'Honolulu',
    country: 'United States',
    iata: 'HNL',
    icao: 'PHNL',
    latitude: 21.3187,
    longitude: -157.9224,
    name: 'Daniel K. Inouye International Airport',
  },
  {
    city: 'Anchorage',
    country: 'United States',
    iata: 'ANC',
    icao: 'PANC',
    latitude: 61.1744,
    longitude: -149.9964,
    name: 'Ted Stevens Anchorage International Airport',
  },
  {
    city: 'Toronto',
    country: 'Canada',
    iata: 'YYZ',
    icao: 'CYYZ',
    latitude: 43.6772,
    longitude: -79.6306,
    name: 'Toronto Pearson International Airport',
  },
  {
    city: 'Vancouver',
    country: 'Canada',
    iata: 'YVR',
    icao: 'CYVR',
    latitude: 49.1939,
    longitude: -123.1844,
    name: 'Vancouver International Airport',
  },
  {
    city: 'Mexico City',
    country: 'Mexico',
    iata: 'MEX',
    icao: 'MMMX',
    latitude: 19.4361,
    longitude: -99.0719,
    name: 'Benito Juarez International Airport',
  },
  {
    city: 'Sao Paulo',
    country: 'Brazil',
    iata: 'GRU',
    icao: 'SBGR',
    latitude: -23.4356,
    longitude: -46.4731,
    name: 'Sao Paulo/Guarulhos International Airport',
  },
  {
    city: 'Buenos Aires',
    country: 'Argentina',
    iata: 'EZE',
    icao: 'SAEZ',
    latitude: -34.8222,
    longitude: -58.5358,
    name: 'Ministro Pistarini International Airport',
  },
  {
    city: 'London',
    country: 'United Kingdom',
    iata: 'LHR',
    icao: 'EGLL',
    latitude: 51.4706,
    longitude: -0.4619,
    name: 'Heathrow Airport',
  },
  {
    city: 'Paris',
    country: 'France',
    iata: 'CDG',
    icao: 'LFPG',
    latitude: 49.0097,
    longitude: 2.5479,
    name: 'Charles de Gaulle Airport',
  },
  {
    city: 'Frankfurt',
    country: 'Germany',
    iata: 'FRA',
    icao: 'EDDF',
    latitude: 50.0379,
    longitude: 8.5622,
    name: 'Frankfurt Airport',
  },
  {
    city: 'Amsterdam',
    country: 'Netherlands',
    iata: 'AMS',
    icao: 'EHAM',
    latitude: 52.3086,
    longitude: 4.7639,
    name: 'Amsterdam Airport Schiphol',
  },
  {
    city: 'Madrid',
    country: 'Spain',
    iata: 'MAD',
    icao: 'LEMD',
    latitude: 40.4719,
    longitude: -3.5626,
    name: 'Adolfo Suarez Madrid-Barajas Airport',
  },
  {
    city: 'Rome',
    country: 'Italy',
    iata: 'FCO',
    icao: 'LIRF',
    latitude: 41.8003,
    longitude: 12.2389,
    name: 'Leonardo da Vinci-Fiumicino Airport',
  },
  {
    city: 'Istanbul',
    country: 'Turkey',
    iata: 'IST',
    icao: 'LTFM',
    latitude: 41.2753,
    longitude: 28.7519,
    name: 'Istanbul Airport',
  },
  {
    city: 'Kyiv',
    country: 'Ukraine',
    iata: 'KBP',
    icao: 'UKBB',
    latitude: 50.345,
    longitude: 30.8947,
    name: 'Boryspil International Airport',
  },
  {
    city: 'Moscow',
    country: 'Russia',
    iata: 'SVO',
    icao: 'UUEE',
    latitude: 55.9726,
    longitude: 37.4146,
    name: 'Sheremetyevo International Airport',
  },
  {
    city: 'Dubai',
    country: 'United Arab Emirates',
    iata: 'DXB',
    icao: 'OMDB',
    latitude: 25.2528,
    longitude: 55.3644,
    name: 'Dubai International Airport',
  },
  {
    city: 'Doha',
    country: 'Qatar',
    iata: 'DOH',
    icao: 'OTHH',
    latitude: 25.2731,
    longitude: 51.6081,
    name: 'Hamad International Airport',
  },
  {
    city: 'Cairo',
    country: 'Egypt',
    iata: 'CAI',
    icao: 'HECA',
    latitude: 30.1219,
    longitude: 31.4056,
    name: 'Cairo International Airport',
  },
  {
    city: 'Johannesburg',
    country: 'South Africa',
    iata: 'JNB',
    icao: 'FAOR',
    latitude: -26.1392,
    longitude: 28.246,
    name: 'O. R. Tambo International Airport',
  },
  {
    city: 'Nairobi',
    country: 'Kenya',
    iata: 'NBO',
    icao: 'HKJK',
    latitude: -1.3192,
    longitude: 36.9278,
    name: 'Jomo Kenyatta International Airport',
  },
  {
    city: 'Delhi',
    country: 'India',
    iata: 'DEL',
    icao: 'VIDP',
    latitude: 28.5562,
    longitude: 77.1,
    name: 'Indira Gandhi International Airport',
  },
  {
    city: 'Singapore',
    country: 'Singapore',
    iata: 'SIN',
    icao: 'WSSS',
    latitude: 1.3644,
    longitude: 103.9915,
    name: 'Singapore Changi Airport',
  },
  {
    city: 'Hong Kong',
    country: 'China',
    iata: 'HKG',
    icao: 'VHHH',
    latitude: 22.308,
    longitude: 113.9185,
    name: 'Hong Kong International Airport',
  },
  {
    city: 'Beijing',
    country: 'China',
    iata: 'PEK',
    icao: 'ZBAA',
    latitude: 40.0799,
    longitude: 116.6031,
    name: 'Beijing Capital International Airport',
  },
  {
    city: 'Shanghai',
    country: 'China',
    iata: 'PVG',
    icao: 'ZSPD',
    latitude: 31.1434,
    longitude: 121.8052,
    name: 'Shanghai Pudong International Airport',
  },
  {
    city: 'Seoul',
    country: 'South Korea',
    iata: 'ICN',
    icao: 'RKSI',
    latitude: 37.4602,
    longitude: 126.4407,
    name: 'Incheon International Airport',
  },
  {
    city: 'Tokyo',
    country: 'Japan',
    iata: 'HND',
    icao: 'RJTT',
    latitude: 35.5494,
    longitude: 139.7798,
    name: 'Tokyo Haneda Airport',
  },
  {
    city: 'Sydney',
    country: 'Australia',
    iata: 'SYD',
    icao: 'YSSY',
    latitude: -33.9461,
    longitude: 151.1772,
    name: 'Sydney Kingsford Smith Airport',
  },
  {
    city: 'Auckland',
    country: 'New Zealand',
    iata: 'AKL',
    icao: 'NZAA',
    latitude: -37.0082,
    longitude: 174.785,
    name: 'Auckland Airport',
  },
];
