FROM node:24-bookworm-slim

WORKDIR /app

RUN npm install --global pnpm@10.32.1

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
COPY oxfmt.config.ts oxlint.config.ts ./
COPY apps/backend/package.json apps/backend/package.json
COPY apps/web/package.json apps/web/package.json
COPY packages/database/package.json packages/database/package.json
RUN pnpm install --frozen-lockfile --ignore-scripts

COPY apps/backend apps/backend
COPY packages/database packages/database
RUN pnpm --filter @workspace/database build && pnpm --filter backend build

CMD ["pnpm", "--filter", "backend", "start"]
